/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.VeterinarioControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoCanales
 */
public class DlgEditarVeterinario extends javax.swing.JDialog {
    
    VeterinarioControlador controlador = new VeterinarioControlador();
    public String idV;
    public String nombreV;
    public String apellidoV;
    public String fechaNacV;
    public String direcV;
    public String celularV;
    public String dniV;

    /**
     * Creates new form DlgEditarVeterinario
     */
    public DlgEditarVeterinario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void cargarDatos(){
        txtIdV.setText(idV);
        txtNombreV.setText(nombreV);
        txtApellidoV.setText(apellidoV);
        txtFechaNacV.setText(fechaNacV);
        txtDireccionV.setText(direcV);
        txtCelularV.setText(celularV);
        txtDniV.setText(dniV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloEditarV = new javax.swing.JLabel();
        lblNombreV = new javax.swing.JLabel();
        txtNombreV = new javax.swing.JTextField();
        lblApellidoV = new javax.swing.JLabel();
        txtApellidoV = new javax.swing.JTextField();
        lblDireccionV = new javax.swing.JLabel();
        txtDireccionV = new javax.swing.JTextField();
        lblFechaNacV = new javax.swing.JLabel();
        txtFechaNacV = new javax.swing.JTextField();
        lbldniV = new javax.swing.JLabel();
        txtDniV = new javax.swing.JTextField();
        lblVelularV = new javax.swing.JLabel();
        txtCelularV = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblIdV = new javax.swing.JLabel();
        txtIdV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTituloEditarV.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTituloEditarV.setText("Editar Veterinario");

        lblNombreV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreV.setText("Nombre:");

        txtNombreV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblApellidoV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblApellidoV.setText("Apellidos:");

        txtApellidoV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblDireccionV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDireccionV.setText("Dirección:");

        txtDireccionV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblFechaNacV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFechaNacV.setText("Fecha de Nacimiento:");

        txtFechaNacV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lbldniV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbldniV.setText("Nº DNI:");

        txtDniV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDniV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniVActionPerformed(evt);
            }
        });

        lblVelularV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVelularV.setText("Nº Celular:");

        txtCelularV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblIdV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIdV.setText("ID:");

        txtIdV.setEditable(false);
        txtIdV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldniV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellidoV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoV))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloEditarV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIdV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblFechaNacV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaNacV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDireccionV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVelularV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloEditarV)
                    .addComponent(lblIdV)
                    .addComponent(txtIdV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreV)
                    .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoV)
                    .addComponent(txtApellidoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionV)
                    .addComponent(txtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacV)
                    .addComponent(txtFechaNacV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldniV)
                    .addComponent(txtDniV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelularV)
                    .addComponent(txtCelularV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombre = txtNombreV.getText();
        String apellido = txtApellidoV.getText();
        String fecha_nac = txtFechaNacV.getText();
        String direccion = txtDireccionV.getText();
        String n_cel = txtCelularV.getText();
        String n_dni = txtDniV.getText();
        int id = Integer.parseInt(txtIdV.getText());
        boolean esCorrecto = controlador.actualizarVeterinario(id, nombre, apellido, fecha_nac, direccion, n_cel, n_dni);
        if(esCorrecto){
            JOptionPane.showMessageDialog(null, "Se actualizó el veterinario correctamente", "Mensaje del Sitema", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(null, "No se actualizó el veterinario correctamente", "Mensaje del Sitema", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarDatos();
    }//GEN-LAST:event_formWindowOpened

    private void txtDniVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniVActionPerformed
        
    }//GEN-LAST:event_txtDniVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblApellidoV;
    private javax.swing.JLabel lblDireccionV;
    private javax.swing.JLabel lblFechaNacV;
    private javax.swing.JLabel lblIdV;
    private javax.swing.JLabel lblNombreV;
    private javax.swing.JLabel lblTituloEditarV;
    private javax.swing.JLabel lblVelularV;
    private javax.swing.JLabel lbldniV;
    private javax.swing.JTextField txtApellidoV;
    private javax.swing.JTextField txtCelularV;
    private javax.swing.JTextField txtDireccionV;
    private javax.swing.JTextField txtDniV;
    private javax.swing.JTextField txtFechaNacV;
    private javax.swing.JTextField txtIdV;
    private javax.swing.JTextField txtNombreV;
    // End of variables declaration//GEN-END:variables
}
