/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.VeterinarioControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoCanales
 */
public class DlgNuevoVeterinario extends javax.swing.JDialog {
    
    VeterinarioControlador controlador = new VeterinarioControlador();

    /**
     * Creates new form DlgNuevoVeterinario
     */
    public DlgNuevoVeterinario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombreV = new javax.swing.JLabel();
        lblApellidoV = new javax.swing.JLabel();
        lblDireccionV = new javax.swing.JLabel();
        lblFechaNacV = new javax.swing.JLabel();
        lbldniV = new javax.swing.JLabel();
        lblVelularV = new javax.swing.JLabel();
        txtNombreV = new javax.swing.JTextField();
        txtApellidoV = new javax.swing.JTextField();
        txtDireccionV = new javax.swing.JTextField();
        txtFechaNacV = new javax.swing.JTextField();
        txtDniV = new javax.swing.JTextField();
        txtCelularV = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Veterinario");

        lblNombreV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreV.setText("Nombre:");

        lblApellidoV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblApellidoV.setText("Apellidos:");

        lblDireccionV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDireccionV.setText("Dirección:");

        lblFechaNacV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFechaNacV.setText("Fecha de Nacimiento:");

        lbldniV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbldniV.setText("Nº DNI:");

        lblVelularV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblVelularV.setText("Nº Celular:");

        txtNombreV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtApellidoV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtDireccionV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtFechaNacV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtDniV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        txtCelularV.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldniV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellidoV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoV, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblFechaNacV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaNacV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDireccionV)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVelularV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreV)
                    .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoV)
                    .addComponent(txtApellidoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionV)
                    .addComponent(txtDireccionV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacV)
                    .addComponent(txtFechaNacV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldniV)
                    .addComponent(txtDniV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelularV)
                    .addComponent(txtCelularV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombreV.getText();
        String apellido = txtApellidoV.getText();
        String fecha_nac = txtFechaNacV.getText();
        String direccion = txtDireccionV.getText();
        String n_cel = txtCelularV.getText();
        String n_dni = txtDniV.getText();
        boolean esCorrecto = controlador.agregarVeterinario(nombre, apellido, fecha_nac, direccion, n_cel, n_dni);
        if(esCorrecto){
            JOptionPane.showMessageDialog(null, "Se agregó el veterinario correctamente", "Mensaje del Sitema", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(null, "No se agregó el veterinario correctamente", "Mensaje del Sitema", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidoV;
    private javax.swing.JLabel lblDireccionV;
    private javax.swing.JLabel lblFechaNacV;
    private javax.swing.JLabel lblNombreV;
    private javax.swing.JLabel lblVelularV;
    private javax.swing.JLabel lbldniV;
    private javax.swing.JTextField txtApellidoV;
    private javax.swing.JTextField txtCelularV;
    private javax.swing.JTextField txtDireccionV;
    private javax.swing.JTextField txtDniV;
    private javax.swing.JTextField txtFechaNacV;
    private javax.swing.JTextField txtNombreV;
    // End of variables declaration//GEN-END:variables
}
