/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.VeterinarioControlador;
import java.awt.Frame;

/**
 *
 * @author FernandoCanales
 */
public class DlgVistaVeterinario extends javax.swing.JDialog {
    
    Frame parentFrame;
    VeterinarioControlador controlador = new VeterinarioControlador();

    /**
     * Creates new form DlgVistaVeterinario
     * @param parent
     * @param modal
     */
    public DlgVistaVeterinario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListaVeterinario();
    }
    
    public void cargarListaVeterinario() {
        try {
            tblVeterinarios.setModel(controlador.listarVeterinario());
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloVeterinario = new javax.swing.JLabel();
        srcVeterinarios = new javax.swing.JScrollPane();
        tblVeterinarios = new javax.swing.JTable();
        btnNuevoVeterinario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloVeterinario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTituloVeterinario.setText("Veterinarios");

        tblVeterinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        srcVeterinarios.setViewportView(tblVeterinarios);

        btnNuevoVeterinario.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnNuevoVeterinario.setText("Nuevo Veterinario");
        btnNuevoVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVeterinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(srcVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloVeterinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoVeterinario)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloVeterinario)
                    .addComponent(btnNuevoVeterinario))
                .addGap(45, 45, 45)
                .addComponent(srcVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVeterinarioActionPerformed
        DlgNuevoVeterinario dlgnuevoveterinario = new DlgNuevoVeterinario(parentFrame, true);
        dlgnuevoveterinario.setVisible(true);
        cargarListaVeterinario();
    }//GEN-LAST:event_btnNuevoVeterinarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoVeterinario;
    private javax.swing.JLabel lblTituloVeterinario;
    private javax.swing.JScrollPane srcVeterinarios;
    private javax.swing.JTable tblVeterinarios;
    // End of variables declaration//GEN-END:variables
}
